require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require '../tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_rdoc ['README', 'LICENSE', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "test and package gem"
task :default => [:test, :package]

# get @VERSION from commandline
@VERSION =  '1.2.2'
NAME="activerdf_rdflite"
GEMNAME="#{NAME}-#{@VERSION}.gem"

# define package task
setup_gem(NAME,@VERSION) do |spec|
  spec.summary = "an RDF database for usage in ActiveRDF (based on sqlite3)" 
  spec.description = spec.summary
  spec.author="Eyal Oren <eyal.oren@deri.org"
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.add_dependency('uuidtools')
  spec.add_dependency('activerdf', '>= 1.2')
  spec.add_dependency('sqlite3-ruby', '>= 1.2.1')
end

task :install => [:package] do
  sh %{sudo gem install pkg/#{NAME}-#{ActiveRdfVersion}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{NAME}}
end

task :reinstall => [:uninstall, :install]

task :upload => :package do |task|
  sh "scp pkg/#{GEMNAME} eyal@activerdf.org:/home/eyal/webs/activerdf/gems/"
end

