require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require '../tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_rdoc ['README', 'LICENSE', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "test and package gem"
task :default => [:test, :package]

# get @VERSION from commandline
@VERSION =  '0.2'
NAME="activerdf_sesame"
GEMNAME="#{NAME}-#{@VERSION}.gem"

# which files should go into the gem?
PKG_FILES = FileList[
  'ext/*.jar',
  '[A-Z]*',
  'lib/**/*.rb',
  'test/**/*',
]

# define package task
setup_gem(NAME,@VERSION) do |spec|
  spec.summary = "an RDF database for usage in ActiveRDF (based on sesame2)" 
  spec.description = spec.summary
  spec.author="Benjamin Heitmann <benjamin.heitmann@deri.org>"
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.add_dependency('activerdf', '>= 1.2')
  spec.files = PKG_FILES.to_a
  
end



task :install => [:package] do
  sh %{sudo gem install pkg/#{NAME}-#{@VERSION}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{NAME}}
end

task :reinstall => [:uninstall, :install]

task :upload => :package do |task|
  sh "scp pkg/#{GEMNAME} eyal@activerdf.org:/home/eyal/webs/activerdf/gems/"
end

