require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

desc "Does a full compile, test run"
task :default => [:test, :package]

version="xx"
name="activerdf_yars"

setup_gem(name, version) do |spec|
  spec.summary = "ActiveRDF adapter to YARS RDF store" 
  spec.description = spec.summary
  spec.author="Eyal Oren <eyal.oren@deri.org"
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.add_dependency('activerdf', '>= 0.9.2')
end


task :install => [:test, :package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end

task :reinstall => [:uninstall, :install]
