require 'meta_project'
require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/contrib/xforge'
require 'rubygems'
require 'fileutils'
require '../tools/rakehelp'

$version  = IO.read('VERSION').strip
$name     = 'activerdf_redland'
$project  = MetaProject::Project::XForge::RubyForge.new('activerdf')
$distdir  = "#$name-#$version"

# setup tests
setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

desc "Does a full compile, test run"
task :default => [:test, :package]

setup_gem($name, $version) do |spec|
  spec.summary = "ActiveRDF adapter to Redland RDF store" 
  spec.description = spec.summary
  spec.author="Eyal Oren <eyal.oren@deri.org"
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.add_dependency('activerdf', '>= 1.6.4')
	spec.requirements << 'librdf0 (Redland)'
	spec.requirements << 'librdf-ruby (Redland Ruby bindings)'
end

task :verify_rubyforge do
  raise "RUBYFORGE_USER environment variable not set!" unless ENV['RUBYFORGE_USER']
  raise "RUBYFORGE_PASSWORD environment variable not set!" unless ENV['RUBYFORGE_PASSWORD']
end

desc "release #$name-#$version gem on RubyForge"
task :release => [ :clean, :verify_rubyforge, :package ] do
  release_files = FileList["pkg/#$distdir.gem"]
  Rake::XForge::Release.new($project) do |release|
    release.user_name     = ENV['RUBYFORGE_USER']
    release.password      = ENV['RUBYFORGE_PASSWORD']
    release.files         = release_files.to_a
    release.release_name  = "#$name #$version"
    release.package_name  = "activerdf-redland"
		release.release_notes = ""

    changes = []
    File.open("CHANGELOG") do |file|
      current = true

      file.each do |line|
        line.chomp!
				if current and line =~ /^==/
					current = false; next 
				end
        break if line.empty? and not current
        changes << line
      end
    end
    release.release_changes = changes.join("\n")
  end
end
